# Generated by Django 2.1.7 on 2019-03-30 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pen_pal', '0003_auto_20190330_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
                ('gender', models.TextField(choices=[('Male', 'Male'), ('Female', 'Female')])),
                ('political_status', models.TextField(choices=[('Democrat', 'Democrat'), ('Republican', 'Republican'), ('Libertarian', 'Libertarian'), ('Green Party', 'Green Party'), ('Other', 'Other')])),
                ('interested_topics', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pen_pal.Topic')),
            ],
            options={
                'ordering': ['last_name'],
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='interested_topics',
        ),
        migrations.AlterField(
            model_name='conversation',
            name='user1_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user1', to='pen_pal.Users'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='user2_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user2', to='pen_pal.Users'),
        ),
        migrations.AlterField(
            model_name='conversationtext',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pen_pal.Users'),
        ),
        migrations.AlterField(
            model_name='matches',
            name='user1_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='match_user1', to='pen_pal.Users'),
        ),
        migrations.AlterField(
            model_name='matches',
            name='user2_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='match_user2', to='pen_pal.Users'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pen_pal.Users'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pen_pal.Users'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
