# Generated by Django 2.1.7 on 2019-03-30 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pen_pal', '0004_auto_20190330_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='name',
        ),
    ]
