# Generated by Django 2.1.7 on 2019-03-30 18:54

from django.db import migrations


class Migration(migrations.Migration):
    atomic=False
    dependencies = [
        ('pen_pal', '0005_remove_users_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
