# Generated by Django 2.1.7 on 2019-03-31 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pen_pal', '0006_auto_20190330_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view', models.TextField(choices=[('Strong Agree with Liberal View', 'Strong Agree with Liberal View'), ('Leaning towards Liberal View', 'Leaning towards Liberal View'), ('Neutral', 'Neutral'), ('Leaning towards Conservative View', 'Leaning towards Conservative View'), ('Strongly Agree with Conservative View', 'Strongly Agree with Conservative View')])),
                ('progress', models.IntegerField()),
                ('interest_other_side', models.BooleanField()),
                ('topic_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pen_pal.Topic')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pen_pal.User')),
            ],
            options={
                'ordering': ['user_id'],
            },
        ),
    ]
